# Generated by Django 5.1.7 on 2025-05-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='clave',
            field=models.CharField(default='123456', max_length=128),
        ),
    ]
